import React, { useEffect, useState } from 'react';
import { UserPlus, ShieldCheck, Users } from 'lucide-react';
import { OfficialDbRecord } from '../types';

export const OfficialsAccountManager: React.FC<{ token:string; isAdmin:boolean }> = ({ token, isAdmin }) => {
  const [officials,setOfficials]=useState<OfficialDbRecord[]>([]); const [open,setOpen]=useState(false); const [username,setUsername]=useState(''); const [displayName,setDisplayName]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  const load=async()=>{ const r=await fetch('/api/officials',{headers:{Authorization:`Bearer ${token}`}}); if(r.ok){const d=await r.json();setOfficials(d.officials||[]);} };
  useEffect(()=>{load()},[token]);
  const create=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{const r=await fetch('/api/officials',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({username,display_name:displayName,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to create account');setUsername('');setDisplayName('');setPassword('');setOpen(false);load();}catch(err){setError(err instanceof Error?err.message:'Unable to create account')}finally{setSaving(false)}};
  return <section className="rounded-2xl border border-sky-200 bg-white p-5 shadow-sm">
    <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="rounded-xl bg-sky-100 p-2 text-sky-700"><Users className="h-5 w-5"/></div><div><h3 className="text-sm font-semibold">Official Accounts</h3><p className="text-xs text-stone-500">Accounts are stored in the PostgreSQL <span className="font-mono">officials</span> table.</p></div></div>{isAdmin&&<button onClick={()=>setOpen(v=>!v)} className="inline-flex items-center gap-1.5 rounded-xl bg-sky-700 px-3 py-2 text-xs font-semibold text-white"><UserPlus className="h-3.5 w-3.5"/>Add sub-official</button>}</div>
    {isAdmin&&open&&<form onSubmit={create} className="mt-4 grid gap-2 border-t border-stone-100 pt-4 sm:grid-cols-3"><input required value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username" className="rounded-lg border border-stone-200 px-3 py-2 text-xs"/><input required value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Display name" className="rounded-lg border border-stone-200 px-3 py-2 text-xs"/><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (8+ chars)" className="rounded-lg border border-stone-200 px-3 py-2 text-xs"/><button disabled={saving} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white sm:col-span-3">{saving?'Creating...':'Create sub-official account'}</button>{error&&<div className="text-xs text-rose-700 sm:col-span-3">{error}</div>}</form>}
    <div className="mt-4 grid gap-2 sm:grid-cols-2">{officials.map(o=><div key={o.id} className="rounded-xl border border-stone-200 bg-stone-50 p-3"><div className="flex items-center justify-between"><span className="text-xs font-semibold">{o.display_name}</span><span className="rounded-full bg-white px-2 py-1 text-[10px] font-mono">{o.role==='admin'?'ADMIN':'SUB-OFFICIAL'}</span></div><div className="mt-1 text-[10px] text-stone-500">@{o.username} · {o.active?'Active':'Inactive'}</div></div>)}</div>
    <div className="mt-3 flex gap-2 text-[11px] text-stone-500"><ShieldCheck className="h-4 w-4 text-sky-600"/>Sub-official accounts cannot create additional official accounts.</div>
  </section>
}
